import express from 'express';
import cors from 'cors';
import dotenv from 'dotenv';
import authRoutes from './routes/auth.js';
import componentesRoutes from './routes/componentes.js';
import casosRoutes from './routes/casos.js';
import planesRoutes from './routes/planes.js';
import resultadosRoutes from './routes/resultados.js';
import usuariosRoutes from './routes/usuarios.js';
dotenv.config();
const app = express();
app.use(cors()); app.use(express.json());
app.use('/api/auth', authRoutes);
app.use('/api/componentes', componentesRoutes);
app.use('/api/casos', casosRoutes);
app.use('/api/planes', planesRoutes);
app.use('/api/resultados', resultadosRoutes);
app.use('/api/usuarios', usuariosRoutes);
const PORT = process.env.PORT || 4000;
app.listen(PORT, ()=> console.log(`Backend escuchando en ${PORT}`));
